import { Review, GarageGem, NewsItem, GalleryImage } from '@/types';

export const reviews: Review[] = [
  {
    id: '1',
    title: 'The Future of EVs in India: A Comprehensive Market Analysis',
    category: 'Analysis',
    excerpt: 'India sold over 2 million electric vehicles in FY 24-25, with two-wheelers leading the charge at 59.4% market share. Discover the trends shaping the future of mobility.',
    image: 'https://images.unsplash.com/photo-1593941707882-a5bba14938c7?w=800&q=80',
    date: '2026-04-13',
    readTime: '10 min read',
    url: '/articles/Future of EVs in India.pdf',
  },
  {
    id: '2',
    title: 'Li-NMC vs. Li-LFP: Which Battery Chemistry Wins in India?',
    category: 'Technology',
    excerpt: 'From energy density to thermal stability, we break down why LFP batteries are becoming the preferred choice for India\'s unique climatic challenges.',
    image: 'https://images.unsplash.com/photo-1568605117036-5fe5e7bab0b7?w=800&q=80',
    date: '2026-04-10',
    readTime: '12 min read',
    url: '/articles/Future of EVs in India.pdf',
  },
  {
    id: '3',
    title: 'Range Anxiety and the Battery Swapping Solution',
    category: 'Infrastructure',
    excerpt: 'Is Battery as a Service (BaaS) the missing link for mass EV adoption? Exploring how swapping stations could revolutionize urban commuting.',
    image: 'https://images.unsplash.com/photo-1594535182308-8ffefbb661e1?w=800&q=80',
    date: '2026-04-05',
    readTime: '8 min read',
    url: '/articles/Future of EVs in India.pdf',
  },
];

export const garageGems: GarageGem[] = [];

export const news: NewsItem[] = [
  {
    id: '1',
    title: 'India Hits 2 Million EV Sales Milestone in FY 24-25',
    category: 'Industry News',
    date: '2026-04-13',
    readTime: '4 min read',
    url: '/articles/Future of EVs in India.pdf',
  },
  {
    id: '2',
    title: 'Two-Wheeler Segment Dominates Indian EV Market with 59% Share',
    category: 'Market Trends',
    date: '2026-04-11',
    readTime: '5 min read',
    url: '/articles/Future of EVs in India.pdf',
  },
  {
    id: '3',
    title: 'Government Considering Standardization for Battery Swapping',
    category: 'Policy',
    date: '2026-04-08',
    readTime: '6 min read',
    url: '/articles/Future of EVs in India.pdf',
  },
];

export const galleryImages: GalleryImage[] = [
  {
    id: '1',
    src: '/images/IMG_1854_SnapseedCopy.webp',
    alt: 'Classic automotive profile - Side view',
    width: 3689,
    height: 2075,
    title: 'Midnight Drive',
    description: 'A sleek sports car captured during a late-night photoshoot, showcasing the perfect curves and lighting.',
    category: 'Sports Cars',
    tags: ['sports car', 'night photography', 'automotive', 'luxury'],
    dateTaken: '2024-01-15',
    camera: 'Sony A7R IV',
    lens: 'FE 24-70mm f/2.8 GM',
    aperture: 'f/2.8',
    shutterSpeed: '1/125',
    iso: 100,
    location: 'Mumbai, India',
    featured: true,
  },
  {
    id: '2',
    src: '/images/IMG_2880_SnapseedCopy.webp',
    alt: 'Automotive detail - Front perspective',
    width: 1920,
    height: 1080,
    title: 'Urban Explorer',
    description: 'City streets come alive with this dynamic shot of a modern SUV navigating urban landscapes.',
    category: 'SUV',
    tags: ['SUV', 'urban', 'city driving', 'modern'],
    dateTaken: '2024-02-20',
    camera: 'Sony A7R IV',
    lens: 'FE 16-35mm f/2.8 GM',
    aperture: 'f/4.0',
    shutterSpeed: '1/200',
    iso: 200,
    location: 'Delhi, India',
    featured: false,
  },
  {
    id: '3',
    src: '/images/IMG_2875_SnapseedCopy.webp',
    alt: 'Dynamic driving shot - Rear view',
    width: 1920,
    height: 1080,
    title: 'Speed Demon',
    description: 'Capturing the raw power and motion of a high-performance vehicle in action.',
    category: 'Sports Cars',
    tags: ['sports car', 'motion', 'performance', 'dynamic'],
    dateTaken: '2024-03-10',
    camera: 'Sony A7R IV',
    lens: 'FE 70-200mm f/2.8 GM OSS',
    aperture: 'f/3.2',
    shutterSpeed: '1/400',
    iso: 100,
    location: 'Pune, India',
    featured: true,
  },
];
